site_name: Dauto
site_url: https://gaspect.github.io/dauto
repo_url: https://github.com/gaspect/dauto

theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: teal
        accent: teak

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences

nav:
    - Home: index.md
    - API:
        dauto.database: dauto/database.md
        dauto.admin: dauto/admin.md
        dauto.signals: dauto/signals.md
        dauto.drf: dauto/drf/__init__.md
        dauto.drf.viewsets.mixin: dauto/drf/viewsets/mixin.md
        dauto.drf.permission: dauto/drf/permission.md
        dauto.drf.versioning: dauto/drf/versioning.md
        dauto.drf.serializers: dauto/drf/serializers.md
        dauto.drf.throttling: dauto/drf/throttling.md
        dauto.drf.reverse: dauto/drf/reverse.md
        dauto.polymorphic:  dauto/polymorphic.md
