[project]
name = "dauto"
version = "0.0.3"

authors = [
    {name = "Jesús Enrique Fuentes González", email = "jesusefg12@gmail.com"},
]

description = "A toolkit for django common usecases"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
